@startuml consulter-restaurants

RestaurantListFrame -> RestaurantListFrame : launch()
activate RestaurantListFrame

RestaurantListFrame -> RestaurantListController : initialize()
activate RestaurantListController

RestaurantListController -> RestaurantFacade : getAllRestaurants()
activate RestaurantFacade

RestaurantFacade -> PostGresRestaurantDAO : getAllRestaurants()
activate PostGresRestaurantDAO

PostGresRestaurantDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres

ConnectionPostGres --> PostGresRestaurantDAO : Connection
deactivate ConnectionPostGres

PostGresRestaurantDAO --> RestaurantFacade : return List<Restaurants>
deactivate PostGresRestaurantDAO


RestaurantFacade --> RestaurantListController : return List<Restaurants>
deactivate RestaurantFacade

RestaurantListController -> RestaurantListController : addDeleteButton()
RestaurantListController -> RestaurantListController : addUpdateButton()
RestaurantListController -> RestaurantListController : addDetailsButton()

deactivate RestaurantListController
deactivate RestaurantListFrame
@enduml