
@startuml consultOne

PersonalAccountFrame -> PersonalAccountFrame : launch()
activate PersonalAccountFrame

PersonalAccountFrame -> PersonalAccountController: consultOne(event)
activate PersonalAccountController

PersonalAccountController -> UserFacade: getById(Int id)
activate UserFacade

UserFacade -> PostGresUserDAO : getById(Int id)
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return User
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> PersonalAccountController : return User
deactivate PersonalAccountController
deactivate PersonalAccountFrame

@enduml
