
@startuml initialize-all

AllAccountsFrame -> AllAccountsFrame : launch()
activate AllAccountsFrame

AllAccountsFrame -> AllAccountsController: initialize()
activate AllAccountsController

AllAccountsController -> AllAccountsController: consultAll()

AllAccountsController -> UserFacade: getAllUser()
activate UserFacade

UserFacade -> PostGresUserDAO : getAll()
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return List<User>
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> AllAccountsController : return List<User>

AllAccountsController -> AllAccountsController: consultAskDelete()

AllAccountsController -> UserFacade: getAskDelete()
activate UserFacade

UserFacade -> PostGresUserDAO : getAskDelete()
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return List<User>
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> AllAccountsController : return List<User>
deactivate AllAccountsController
deactivate AllAccountsFrame

deactivate AllAccountsController
deactivate AllAccountsFrame

@enduml
