
@startuml update

AllAccountsFrame -> AllAccountsFrame : launch()
activate AllAccountsFrame

AllAccountsFrame -> AllAccountsController: update(event)
activate AllAccountsController

AllAccountsController -> UserFacade: update(User user)
activate UserFacade

UserFacade -> PostGresUserDAO : update(User user)
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return Boolean
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> AllAccountsController : return Boolean
deactivate AllAccountsController
deactivate AllAccountsFrame

@enduml
