
@startuml askDelete

PersonalAccountFrame -> PersonalAccountFrame : launch()
activate PersonalAccountFrame

PersonalAccountFrame -> PersonalAccountController: askDelete(event)
activate PersonalAccountController

PersonalAccountController -> UserFacade: update(User user)
activate UserFacade

UserFacade -> PostGresUserDAO : update(User user)
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return Boolean
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> PersonalAccountController : return Boolean
deactivate PersonalAccountController
deactivate PersonalAccountFrame

@enduml
