

@startuml consultAll

AllAccountsFrame -> AllAccountsFrame : launch()
activate AllAccountsFrame

AllAccountsFrame -> AllAccountsController: consultAll(event)
activate AllAccountsController

AllAccountsController -> UserFacade: getAllUser()
activate UserFacade

UserFacade -> PostGresUserDAO : getAll()
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return List<User>
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> AllAccountsController : return List<User>
deactivate AllAccountsController
deactivate AllAccountsFrame

@enduml
