
@startuml consultOne

UserFrame -> UserFrame : launch()
activate UserFrame

UserFrame -> UserController: consultOne(event)
activate UserController

UserController -> UserFacade: getInformationsByEmail(String email)
activate UserFacade

UserFacade -> PostGresUserDAO : getByEmail(String email)
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return User
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> UserController : return User
deactivate UserController
deactivate UserFrame

@enduml
