
@startuml delete

AllAccountsFrame -> AllAccountsFrame : launch()
activate AllAccountsFrame

AllAccountsFrame -> AllAccountsController: delete(event)
activate AllAccountsController

AllAccountsController -> UserFacade: delete(Int id)
activate UserFacade

UserFacade -> PostGresUserDAO : delete(Int id)
activate PostGresUserDAO

PostGresUserDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresUserDAO : return Connection
deactivate ConnectionPostGres
PostGresUserDAO --> UserFacade : return Boolean
deactivate PostGresUserDAO
deactivate UserFacade

UserFacade --> AllAccountsController : return Boolean
deactivate AllAccountsController
deactivate AllAccountsFrame

@enduml
