@startuml
MealFrame -> MealFrame : launch()
activate MealFrame

MealFrame -> MealController: pressed(event)
activate MealController

MealController -> MealFacade: update(int idMeal)
activate MealFacade

MealFacade -> PostGresMealDAO : update(int idMeal)
activate PostGresMealDAO

PostGresMealDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresMealDAO : return Connection
deactivate ConnectionPostGres
PostGresMealDAO --> MealFacade : return Boolean
deactivate PostGresMealDAO
deactivate MealFacade

MealFacade --> MealController : return Boolean
deactivate MealController
deactivate MealFrame


@enduml
