@startuml
activate PlacementFrame
PlacementFrame -> PlacementFrame : launch()
PlacementFrame -> PlacementController : initialize()
activate PlacementController
PlacementFrame -> PlacementController: addTable(ActionEvent event)


PlacementController -> PlacementController: switchToTable()
deactivate PlacementFrame

PlacementController -> TableFrame : launch()
activate TableFrame

TableFrame -> TableController : initialize()
activate TableController
deactivate PlacementController

TableController -> AllTablesController : getAllTables()
deactivate TableController
activate AllTablesController

AllTablesController -> AllTablesController : selectionTable()
AllTablesController -> LocalStorage : write(Table)
activate LocalStorage
deactivate LocalStorage
AllTablesController -> AllTablesController : switchToPlacementFrame()
deactivate TableFrame
AllTablesController -> PlacementFrame : launch()
deactivate AllTablesController
activate PlacementFrame

PlacementFrame -> PlacementFrame : initialize()



@enduml
