
@startuml initialize-manager

EventManagerFrame -> EventManagerFrame : launch()
activate EventManagerFrame

EventManagerFrame -> EventManagerController: initialize()
activate EventManagerController

EventManagerController -> EventFacade: getAllEvent()
activate EventFacade

EventFacade -> PostGresEventDAO : getAll()
activate PostGresEventDAO

PostGresEventDAO -> ConnectionPostGres : getConnection()
activate ConnectionPostGres
ConnectionPostGres --> PostGresEventDAO : return Connection
deactivate ConnectionPostGres
PostGresEventDAO --> EventFacade : return List<Event>
deactivate PostGresEventDAO
deactivate EventFacade

EventFacade --> EventManagerController : return List<Event>
deactivate EventManagerController
deactivate EventManagerFrame

@enduml
